### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by barrettshepherd** [JamesChevalier/Launch-Soon#2]
It dosent check for duplicates or check if its actually an email.

**Comment by JamesChevalier** [comment]
It should be checking for dupes... This line should be inserting into the DB unless it (the hash) already exists:

$insertinto = mysql_query("INSERT IGNORE INTO interested (email, hash, invites) VALUES ('$email', '$hashed', '$invites')")

Then, if no updates are made (if the hash is already present), it will pull the existing hash and number of invites this user has accrued & display those (the hash is used to create the custom URL) in the page.

Ideally, I'd like to include some way (a cookie?) to determine if a user has already submitted their email address.  This way, if someone goes to the main page (/index.php) they're automatically displayed their invite URL and # of invites.

**Comment by JamesChevalier** [comment]
I added some email validation in my latest push:
https://github.com/JamesChevalier/Launch-Soon/commit/0f964ff9d1f2f7fa951f7e1819837e945f041f68

I'm new to git, so I don't know the standards/etiquette on handling issues.  I'm going to close this issue, because it seems to me that both duplicates & verification have been handled.  If I'm wrong, please re-open the issue or submit a new one (whichever way is best or more proper).

Thanks again for taking the time to submit issues to my project!
