### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by texjer** [JamesChevalier/Launch-Soon#3]
http://www.artcombinator.com

I'm excited with how this is coming together, but I'm getting an error.  This could just be my inexperience with hard-editting MySQL, so I'm attaching a screenshot of [my table](http://i.imgur.com/Mv9VF.jpg)

**Comment by JamesChevalier** [comment]
The error that you're seeing is:
Fatal error: Call to undefined function: filter_var()

I believe this might be occurring because your host server is running a PHP version less than 5.2.0.
I think you'll either need to upgrade PHP or install the PECL Filter extension (http://pecl.php.net/package/filter).

**Comment by texjer** [comment]
Yup, that's it. My host said it was running 5, but I guess it wasn't. I just added this line to my .htaccess file:
AddType x-mapp-php5 .php

This is very slick! I added some code in the header to give attribution.
